- name: Create instance
  hosts: localhost
  tasks:
    - name: create instance with metadata options
      amazon.aws.ec2_instance:
        name: "ansible-test"
        instance_type: t3.micro
        image_id: ami-123456
        tags:
          Environment: Testing
